@echo on

SET MASTER_NAME=Ubuntu 22.04 LTS Update 2023-2-6
SET MASTER_IP=192.168.56.49
SET MASTER_USERNAME=root
SET MASTER_PASSWORD=1111

SET BASELAB_NAME=Ubuntu 22.04 LTS Update LAB
SET COUNTER_VM=9

SET VMS_PATH=%USERPROFILE%\VirtualBox VMs
SET VBOXMANAGE_PATH=C:\Program Files\Oracle\VirtualBox\VBoxManage.exe